//
//  The wire form of golden.json, and nothing else.
//
//  Kept apart from the assertions so neither file grows past the lint's
//  ceilings, and so a change of the fixture's SHAPE is a diff in one place.
//  The fixture is generated by make_golden.js from the pinned reference
//  adaptive_engine.js; it is never edited by hand.
//

import Foundation

struct Golden: Decodable {
    let generator: String
    let patternOrder: [String]
    /// The ladders, straight from the reference — so the port can be checked
    /// against them instead of the numbers being retyped here.
    let library: [String: [LibraryRung]]
    /// The two dose grids of §40.2.
    let dose: [String: Grid]
    let scenarios: [Scenario]

    struct LibraryRung: Decodable {
        let name: String
        let w: Double
        let unit: String
        let perSide: Bool
        let kind: String
        let prov: String
        /// The one unit boundary И1 skips.
        let probeOnly: Bool?
    }

    struct Grid: Decodable {
        let min: Int
        let max: Int
        let step: Int
    }

    /// Everything a state snapshot carries, at whatever point it was taken.
    /// Written into a step, a break and a handle pull alike, at the SAME
    /// level as their own fields — hence the two-decodes-of-one-decoder shape
    /// used below.
    struct Snapshot: Decodable {
        let varsAfter: [Int]
        let setsAfter: [Int]
        let dosesAfter: [Int]
        let subAfter: [Int]
        let cutAfter: [Int]
        let shownAfter: [String: [String: Int]]
        let lastHardAfter: [Int]
        let setsHoldAfter: [Int]
        let shownWorkAfter: [Int]
        let shownOrdAfter: [Int]
        let rampWindowAfter: Int
        let weekGainAfter: [Int]
        let weekAgeDaysAfter: Double
    }

    struct Scenario: Decodable {
        let name: String
        let steps: [Step]
        let seed: Seed?            // a scenario may not start from zero
    }

    /// A starting state, so a scenario can exercise behaviour that only
    /// appears after a long history without replaying it step by step.
    struct Seed: Decodable {
        let counter: Int
        let hasBar: Bool
        let vars: [Int]            // by patternOrder, all ten
        let sets: [Int]
        let doses: [Int]
        let sub: [Int]
        let cut: [Int]
        let shown: [String: [String: Int]]
        let failStreak: [Int]
        let lastHard: [Int]
    }

    struct Ex: Decodable {
        let pattern: String
        let variation: Int
        let unit: String
        let load: Int              // the BASE dose
        let perSide: Bool
        let sets: Int
        let restSetSec: Int
        let restExerciseSec: Int
        /// Per-set doses, present only on an uneven plan — the wire form
        /// mirrors `[Int]?` exactly, so its absence is a claim too.
        let loads: [Int]?
        /// §40.4. Present only where the plan carries a probe.
        let probe: Probe?
    }

    /// The probe as the fixture writes it: a different variation of the same
    /// pattern, with its own unit and its own sides.
    struct Probe: Decodable {
        let variation: Int
        let unit: String
        let load: Int
        let perSide: Bool
    }

    // MARK: - Records that carry a snapshot beside their own fields

    struct Step: Decodable {
        let own: StepFields
        let snapshot: Snapshot

        init(from decoder: Decoder) throws {
            own = try StepFields(from: decoder)
            snapshot = try Snapshot(from: decoder)
        }
    }

    /// A step's own fields, beside the snapshot it carries at the same level.
    struct StepFields: Decodable {
        let sessionNumber: Int
        let estimatedTotalMin: Double
        let warmupMin: Int
        let cooldownMin: Int
        let exercises: [Ex]
        let result: String
        let overrides: [String: Int]
        /// The SEVENTH argument of applyFeedback (§40.4). Absent means no
        /// probe number was reported, which pins the unresolved outcome
        /// just as a present one pins the resolved.
        let probes: [String: Int]?
        let skipped: [String]?
        let hasBar: Bool?
        /// The gap. Absent means nil, which pins the calendar-blind path.
        /// SIXTH, deliberately (§40.11 п. 2).
        let gapDays: Double?
        let handles: Handles?
        /// Sets skipped DURING this session. Landed AFTER the feedback.
        let skipSets: [String: Int]?
        /// The cut the feedback left behind, before the skip was added.
        /// Its only job is to make the ordering visible in the fixture
        /// itself: a port that skipped first would have to reproduce this
        /// number too, and it cannot.
        let cutBeforeSkip: [Int]?
        let silentDecay: BreakStep?
        let comeback: ComebackStep?
        let failStreakAfter: [Int]
        let counterAfter: Int
        let lessRunAfter: Int
        let lessHistAfter: [String: Int]
        let returnRunAfter: Int
        let creditPausedAfter: [Int]
    }

    /// applySilentDecay invoked before this step's session — and before the
    /// step's comeback when both are present: the user peeked mid-break, then
    /// came back later.
    struct BreakStep: Decodable {
        let gapDays: Int
        let failStreakAfter: [Int]
        let snapshot: Snapshot

        init(from decoder: Decoder) throws {
            let own = try BreakFields(from: decoder)
            gapDays = own.gapDays
            failStreakAfter = own.failStreakAfter
            snapshot = try Snapshot(from: decoder)
        }
    }

    struct BreakFields: Decodable {
        let gapDays: Int
        let failStreakAfter: [Int]
    }

    struct Comeback: Decodable {
        let gapDays: Int
        let alreadyDecayed: Bool?  // a silent decay hit this break first
        let counterAfter: Int
        let failStreakAfter: [Int]
        let returnRunAfter: Int
        let snapshot: Snapshot

        init(from decoder: Decoder) throws {
            let own = try ComebackFields(from: decoder)
            gapDays = own.gapDays
            alreadyDecayed = own.alreadyDecayed
            counterAfter = own.counterAfter
            failStreakAfter = own.failStreakAfter
            returnRunAfter = own.returnRunAfter
            snapshot = try Snapshot(from: decoder)
        }
    }

    struct ComebackFields: Decodable {
        let gapDays: Int
        let alreadyDecayed: Bool?
        let counterAfter: Int
        let failStreakAfter: [Int]
        let returnRunAfter: Int
    }

    /// One step may carry a SERIES of comebacks — returns in a row with no
    /// session between, each past the first one deeper. The wire form is
    /// either a single snapshot or `{series: [...]}`.
    struct ComebackStep: Decodable {
        let snaps: [Comeback]
        private enum Keys: String, CodingKey { case series }
        init(from decoder: Decoder) throws {
            if let c = try? decoder.container(keyedBy: Keys.self),
               let series = try c.decodeIfPresent([Comeback].self, forKey: .series) {
                snaps = series
            } else {
                snaps = [try Comeback(from: decoder)]
            }
        }
    }

    /// A handle pull, recorded exactly as a settings toggle is: what was
    /// pressed, and the snapshot of the state right after.
    struct Handles: Decodable {
        let easierVariation: [String]?
        let setCut: [String: Int]?
        let snapshot: Snapshot

        init(from decoder: Decoder) throws {
            let own = try HandleFields(from: decoder)
            easierVariation = own.easierVariation
            setCut = own.setCut
            snapshot = try Snapshot(from: decoder)
        }
    }

    struct HandleFields: Decodable {
        let easierVariation: [String]?
        let setCut: [String: Int]?
    }
}
