//
//  GoldenTests.swift
//  Cross-check of the Swift port against the reference JS engine.
//
//  golden.json is generated by make_golden.js from adaptive_engine.js (v2.2.0):
//  7 scenarios (always_plan, mixed, overrides, deload, skips, ceiling, bar) with
//  a full snapshot of every session and the expected levels after each feedback
//  step. Scenarios with the bar module additionally carry hasBar and the
//  pull_bar branch snapshot per step.
//  A divergence in even one number = a port error. Do not edit the fixture by hand.
//

import XCTest
@testable import DredfitCore

// Disambiguate from the Pattern type introduced in the macOS 26 SDK
private typealias Pattern = DredfitCore.Pattern

// MARK: - Fixture model

private struct Golden: Decodable {
    let generator: String
    let patternOrder: [String]
    let scenarios: [Scenario]

    struct Scenario: Decodable {
        let name: String
        let steps: [Step]
    }
    struct Step: Decodable {
        let sessionNumber: Int
        let estimatedTotalMin: Double
        let exercises: [Ex]
        let result: String
        let overrides: [String: Int]
        let skipped: [String]?     // v2.1.1 (absent in fixtures made before it)
        let levelsAfter: [Int]
        let failStreakAfter: [Int]
        // v2.2: present only in scenarios that exercise the bar module
        let hasBar: Bool?          // effective toggle for this step's session
        let barLevelAfter: Int?
        let barStreakAfter: Int?
    }
    struct Ex: Decodable {
        let pattern: String
        let tier: Int
        let unit: String
        let load: Int
        let perSide: Bool
        let sets: Int
        let restSetSec: Int
        let restExerciseSec: Int
    }
}

final class GoldenTests: XCTestCase {

    private func loadGolden() throws -> Golden {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden", withExtension: "json"),
            "golden.json not found in test resources")
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    func testPatternOrderMatchesReference() throws {
        let g = try loadGolden()
        XCTAssertEqual(g.patternOrder, Pattern.ordered.map(\.rawValue),
                       "pattern order diverged from the reference")
    }

    func testAllScenariosMatchReferenceEngine() throws {
        let g = try loadGolden()
        for scenario in g.scenarios {
            var state = EngineState.initial

            for (i, step) in scenario.steps.enumerated() {
                let ctx = "\(scenario.name)/step \(i + 1)"
                if let hasBar = step.hasBar { state.hasBar = hasBar } // v2.2: settings toggle
                let session = Engine.generateSession(state)

                // --- session matches the reference ---
                XCTAssertEqual(session.sessionNumber, step.sessionNumber, ctx)
                XCTAssertEqual(session.estimatedTotalMin, step.estimatedTotalMin,
                               accuracy: 0.051, ctx + " (duration)")
                XCTAssertEqual(session.exercises.count, step.exercises.count, ctx)

                for (ex, ref) in zip(session.exercises, step.exercises) {
                    XCTAssertEqual(ex.pattern.rawValue, ref.pattern, ctx)
                    XCTAssertEqual(ex.tier, ref.tier, ctx + " \(ref.pattern) tier")
                    XCTAssertEqual(ex.unit.rawValue, ref.unit, ctx)
                    XCTAssertEqual(ex.load, ref.load, ctx + " \(ref.pattern) load")
                    XCTAssertEqual(ex.perSide, ref.perSide, ctx)
                    XCTAssertEqual(ex.sets, ref.sets, ctx)
                    XCTAssertEqual(ex.restSetSec, ref.restSetSec, ctx)
                    XCTAssertEqual(ex.restExerciseSec, ref.restExerciseSec, ctx)
                }

                // --- feedback yields the same levels ---
                let result = FeedbackResult(rawValue: step.result)!
                let overrides = Dictionary(uniqueKeysWithValues:
                    step.overrides.map { (Pattern(rawValue: $0.key)!, $0.value) })
                let skipped = Set((step.skipped ?? []).map { Pattern(rawValue: $0)! })
                state = Engine.applyFeedback(state: state, session: session,
                                             result: result, overrides: overrides,
                                             skipped: skipped)

                let levels = Pattern.ordered.map { state.levels[$0]! }
                let streaks = Pattern.ordered.map { state.failStreak[$0]! }
                XCTAssertEqual(levels, step.levelsAfter, ctx + " (levels)")
                XCTAssertEqual(streaks, step.failStreakAfter, ctx + " (failStreak)")

                // v2.2: the vertical branch snapshot
                if let barLevel = step.barLevelAfter {
                    XCTAssertEqual(state.levels[.pullBar], barLevel, ctx + " (bar level)")
                }
                if let barStreak = step.barStreakAfter {
                    XCTAssertEqual(state.failStreak[.pullBar], barStreak, ctx + " (bar streak)")
                }
            }
        }
    }
}
