//
//  GoldenTests.swift
//  Cross-check of the Swift port against the reference JS engine.
//
//  golden.json is generated by make_golden.js from adaptive_engine.js (v2.3.0):
//  9 scenarios (always_plan, mixed, overrides, deload, skips, ceiling, bar,
//  calibration, comeback) with a full snapshot of every session and the
//  expected levels after each feedback step. Scenarios with the bar module
//  additionally carry hasBar and the pull_bar branch snapshot per step.
//  v2.3 scenarios may start from a seeded state and may apply a comeback
//  before a session — both are replayed here exactly as the app would.
//  A divergence in even one number = a port error. Do not edit the fixture by hand.
//

import XCTest
@testable import DredfitCore

// Disambiguate from the Pattern type introduced in the macOS 26 SDK
private typealias Pattern = DredfitCore.Pattern

// MARK: - Fixture model

private struct Golden: Decodable {
    let generator: String
    let patternOrder: [String]
    let scenarios: [Scenario]

    struct Scenario: Decodable {
        let name: String
        let steps: [Step]
        let seed: Seed?            // v2.3: scenario may not start from zero
    }
    /// v2.3: a starting state, so a scenario can exercise behaviour that only
    /// appears after a long history without replaying it step by step.
    struct Seed: Decodable {
        let counter: Int
        let hasBar: Bool
        let levels: [Int]          // by patternOrder
        let failStreak: [Int]
        let barLevel: Int
        let barStreak: Int
    }
    /// v2.3: applyComeback invoked before this step's session.
    struct Comeback: Decodable {
        let gapDays: Int
        let levelsAfter: [Int]
        let failStreakAfter: [Int]
        let counterAfter: Int
        let barLevelAfter: Int?
        let barStreakAfter: Int?
    }
    struct Step: Decodable {
        let sessionNumber: Int
        let estimatedTotalMin: Double
        let exercises: [Ex]
        let result: String
        let overrides: [String: Int]
        let skipped: [String]?     // v2.1.1 (absent in fixtures made before it)
        let levelsAfter: [Int]
        let failStreakAfter: [Int]
        // v2.2: present only in scenarios that exercise the bar module
        let hasBar: Bool?          // effective toggle for this step's session
        let barLevelAfter: Int?
        let barStreakAfter: Int?
        let comeback: Comeback?    // v2.3
    }
    struct Ex: Decodable {
        let pattern: String
        let tier: Int
        let unit: String
        let load: Int
        let perSide: Bool
        let sets: Int
        let restSetSec: Int
        let restExerciseSec: Int
    }
}

final class GoldenTests: XCTestCase {

    private func loadGolden() throws -> Golden {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden", withExtension: "json"),
            "golden.json not found in test resources")
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    /// The fixture must come from the pinned reference version — a fixture
    /// regenerated from the wrong adaptive_engine.js would silently
    /// re-baseline every number instead of catching a port bug.
    func testGeneratorIsThePinnedReferenceVersion() throws {
        let g = try loadGolden()
        XCTAssertEqual(g.generator, "adaptive_engine.js v2.3.0",
                       "golden.json regenerated from an unexpected reference version")
    }

    func testPatternOrderMatchesReference() throws {
        let g = try loadGolden()
        XCTAssertEqual(g.patternOrder, Pattern.ordered.map(\.rawValue),
                       "pattern order diverged from the reference")
    }

    func testAllScenariosMatchReferenceEngine() throws {
        let g = try loadGolden()
        for scenario in g.scenarios {
            var state = EngineState.initial
            if let seed = scenario.seed {
                state.counter = seed.counter
                state.hasBar = seed.hasBar
                for (idx, name) in g.patternOrder.enumerated() {
                    let p = try XCTUnwrap(Pattern(rawValue: name))
                    state.levels[p] = seed.levels[idx]
                    state.failStreak[p] = seed.failStreak[idx]
                }
                state.levels[.pullBar] = seed.barLevel
                state.failStreak[.pullBar] = seed.barStreak
            }

            for (i, step) in scenario.steps.enumerated() {
                let ctx = "\(scenario.name)/step \(i + 1)"
                if let hasBar = step.hasBar { state.hasBar = hasBar } // v2.2: settings toggle
                if let comeback = step.comeback {
                    // v2.3: the app applies this on launch after a break,
                    // before the plan is generated — same order here.
                    state = Engine.applyComeback(state: state, gapDays: comeback.gapDays)
                    XCTAssertEqual(g.patternOrder.map { state.levels[Pattern(rawValue: $0)!] ?? -1 },
                                   comeback.levelsAfter, "\(ctx) levels after comeback")
                    XCTAssertEqual(g.patternOrder.map { state.failStreak[Pattern(rawValue: $0)!] ?? -1 },
                                   comeback.failStreakAfter, "\(ctx) streaks after comeback")
                    XCTAssertEqual(state.counter, comeback.counterAfter,
                                   "\(ctx) comeback must not move the counter")
                    if let barLevel = comeback.barLevelAfter {
                        XCTAssertEqual(state.levels[.pullBar], barLevel, "\(ctx) bar level after comeback")
                    }
                    if let barStreak = comeback.barStreakAfter {
                        XCTAssertEqual(state.failStreak[.pullBar], barStreak, "\(ctx) bar streak after comeback")
                    }
                }
                let session = Engine.generateSession(state)

                // --- session matches the reference ---
                XCTAssertEqual(session.sessionNumber, step.sessionNumber, ctx)
                XCTAssertEqual(session.estimatedTotalMin, step.estimatedTotalMin,
                               accuracy: 0.051, ctx + " (duration)")
                XCTAssertEqual(session.exercises.count, step.exercises.count, ctx)

                for (ex, ref) in zip(session.exercises, step.exercises) {
                    XCTAssertEqual(ex.pattern.rawValue, ref.pattern, ctx)
                    XCTAssertEqual(ex.tier, ref.tier, ctx + " \(ref.pattern) tier")
                    XCTAssertEqual(ex.unit.rawValue, ref.unit, ctx)
                    XCTAssertEqual(ex.load, ref.load, ctx + " \(ref.pattern) load")
                    XCTAssertEqual(ex.perSide, ref.perSide, ctx)
                    XCTAssertEqual(ex.sets, ref.sets, ctx)
                    XCTAssertEqual(ex.restSetSec, ref.restSetSec, ctx)
                    XCTAssertEqual(ex.restExerciseSec, ref.restExerciseSec, ctx)
                }

                // --- feedback yields the same levels ---
                let result = FeedbackResult(rawValue: step.result)!
                let overrides = Dictionary(uniqueKeysWithValues:
                    step.overrides.map { (Pattern(rawValue: $0.key)!, $0.value) })
                let skipped = Set((step.skipped ?? []).map { Pattern(rawValue: $0)! })
                state = Engine.applyFeedback(state: state, session: session,
                                             result: result, overrides: overrides,
                                             skipped: skipped)

                let levels = Pattern.ordered.map { state.levels[$0]! }
                let streaks = Pattern.ordered.map { state.failStreak[$0]! }
                XCTAssertEqual(levels, step.levelsAfter, ctx + " (levels)")
                XCTAssertEqual(streaks, step.failStreakAfter, ctx + " (failStreak)")

                // v2.2: the vertical branch snapshot
                if let barLevel = step.barLevelAfter {
                    XCTAssertEqual(state.levels[.pullBar], barLevel, ctx + " (bar level)")
                }
                if let barStreak = step.barStreakAfter {
                    XCTAssertEqual(state.failStreak[.pullBar], barStreak, ctx + " (bar streak)")
                }
            }
        }
    }
}
