//
//  Cross-check of the Swift port against the reference JS engine.
//
//  golden.json is generated by make_golden.js from the pinned reference
//  adaptive_engine.js: a full snapshot of every session and the expected
//  levels after each feedback step, per scenario. Scenarios may start from
//  a seeded state and may apply a comeback before a session — both are
//  replayed here exactly as the app would.
//  A divergence in even one number = a port error. Do not edit the fixture by hand.
//

import XCTest
@testable import DredfitCore

// Disambiguate from the Pattern type introduced in the macOS 26 SDK
private typealias Pattern = DredfitCore.Pattern

// MARK: - Fixture model

private struct Golden: Decodable {
    let generator: String
    let patternOrder: [String]
    let scenarios: [Scenario]

    struct Scenario: Decodable {
        let name: String
        let steps: [Step]
        let seed: Seed?            // scenario may not start from zero
    }
    /// A starting state, so a scenario can exercise behaviour that only
    /// appears after a long history without replaying it step by step.
    struct Seed: Decodable {
        let counter: Int
        let hasBar: Bool
        let levels: [Int]          // by patternOrder
        let failStreak: [Int]
        let barLevel: Int
        let barStreak: Int
    }
    /// applyComeback invoked before this step's session.
    struct Comeback: Decodable {
        let gapDays: Int
        let alreadyDecayed: Bool?  // silent decay hit this break first
        let levelsAfter: [Int]
        let failStreakAfter: [Int]
        let counterAfter: Int
        let barLevelAfter: Int?
        let barStreakAfter: Int?
        let lessRunAfter: Int?     // a break does not continue a run of "less"
        let lessHistAfter: [String: Int]?   // the appearance window
        let returnRunAfter: Int?   // consecutive returns deepen the drop
        // A comeback carries the cut across and reclamps it to the new band,
        // and on a long break the memory of pain fades.
        let subAfter: [Int]?
        let cutAfter: [Int]?
        let barCutAfter: Int?
        let setsHoldAfter: [Int]?
    }
    /// One step may carry a SERIES of comebacks — returns in a row with no
    /// session between, each past the first one deeper. The wire form is
    /// either a single snapshot (the old shape) or {series: [...]}.
    struct ComebackStep: Decodable {
        let snaps: [Comeback]
        private enum Keys: String, CodingKey { case series }
        init(from decoder: Decoder) throws {
            if let c = try? decoder.container(keyedBy: Keys.self),
               let series = try c.decodeIfPresent([Comeback].self, forKey: .series) {
                snaps = series
            } else {
                snaps = [try Comeback(from: decoder)]
            }
        }
    }
    /// applySilentDecay invoked before this step's session — and before the
    /// step's comeback, when both are present: the user peeked mid-break, then
    /// came back later.
    struct SilentDecay: Decodable {
        let gapDays: Int
        let levelsAfter: [Int]
        let failStreakAfter: [Int]
        let barLevelAfter: Int?
        let barStreakAfter: Int?
        let lessRunAfter: Int?
        let lessHistAfter: [String: Int]?
        let returnRunAfter: Int?   // a decay is not a return
        // A decay is a DESCENT and walks a step of the growth path — on a
        // block floor it takes a SET and leaves the level alone, so
        // `levelsAfter` alone no longer describes where it landed.
        let subAfter: [Int]?
        let cutAfter: [Int]?
        let barCutAfter: Int?
        let setsHoldAfter: [Int]?
    }
    struct Step: Decodable {
        let sessionNumber: Int
        let estimatedTotalMin: Double
        let exercises: [Ex]
        let result: String
        let overrides: [String: Int]
        let skipped: [String]?     // absent in older fixtures
        let levelsAfter: [Int]
        // The sub-step, by patternOrder. Every scenario writes it — growth
        // moves by sub-steps, so without it the fixture would pin almost
        // nothing about the wave.
        let subAfter: [Int]?
        let barSubAfter: Int?
        let failStreakAfter: [Int]
        // present only in scenarios that exercise the bar module
        let hasBar: Bool?          // effective toggle for this step's session
        let barLevelAfter: Int?
        let barStreakAfter: Int?
        let lessRunAfter: Int?     // run of "less" ratings naming nothing
        let lessHistAfter: [String: Int]?   // the appearance window
        let creditPausedAfter: [Int]?   // [pull, pullBar], 1 = credit paused
        let returnRunAfter: Int?   // 0 after any completed session
        let silentDecay: SilentDecay?
        let comeback: ComebackStep?
        // The third coordinate of a position and everything the wave added
        // around it. Every scenario writes them — gating them by scenario
        // shape is exactly the hole P0-5 of the last audit came through — so
        // they are asserted on every step.
        let cutAfter: [Int]?
        let barCutAfter: Int?
        let setsHoldAfter: [Int]?
        let barSetsHoldAfter: Int?
        let shownWorkAfter: [Int]?
        let barShownWorkAfter: Int?
        let shownOrdAfter: [Int]?
        let barShownOrdAfter: Int?
        // The three fields `make_golden.js` never used to snapshot (audit
        // 2026-08-20, S5-1/S5-2) — the hole this wave closed.
        let rampWindowAfter: Int?
        let weekGainAfter: [Int]?
        let barWeekGainAfter: Int?
        let weekAgeDaysAfter: Double?
        /// The gap. Absent means nil, which pins the calendar-blind path of
        /// just as a present one pins.: it is the SIXTH argument now, not the
        /// seventh.
        let gapDays: Double?
        /// The handles the person pulled before this session's plan was
        /// generated, and the state they left behind.
        let handles: Handles?
        /// Sets skipped DURING this session, per movement (spec §38.2).
        /// Landed AFTER the feedback, never before — see `replay`.
        let skipSets: [String: Int]?
        /// The cut the feedback left behind, before the skip was added. Its
        /// only job is to make the ordering visible in the fixture itself: a
        /// port that skipped first would have to reproduce this number too,
        /// and it cannot.
        let cutBeforeSkip: [Int]?
    }
    /// A handle pull, recorded exactly as a settings toggle is: what was
    /// pressed, and the snapshot of the state right after.
    struct Handles: Decodable {
        let easierVariation: [String]?
        let setCut: [String: Int]?
        // v2.27 (§38.1): `shorterSession` is gone from the reference, so it is
        // gone from the wire form. A key the fixture can no longer carry must
        // not stay decodable: it would read as "supported, never exercised".
        let levelsAfter: [Int]?
        let barLevelAfter: Int?
        let failStreakAfter: [Int]?
        let subAfter: [Int]?
        let cutAfter: [Int]?
        let barCutAfter: Int?
        let setsHoldAfter: [Int]?
        let lessRunAfter: Int?
    }
    struct Ex: Decodable {
        let pattern: String
        let tier: Int
        let unit: String
        let load: Int          // the BASE dose
        let perSide: Bool
        let sets: Int
        let restSetSec: Int
        let restExerciseSec: Int
        /// Per-set doses, present only on an uneven plan — the wire form
        /// mirrors `[Int]?` exactly, so its absence is a claim too.
        let loads: [Int]?
    }
}

final class GoldenTests: XCTestCase {

    private func loadGolden() throws -> Golden {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden", withExtension: "json"),
            "golden.json not found in test resources")
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    /// The fixture must come from the pinned reference version — a fixture
    /// regenerated from the wrong adaptive_engine.js would silently
    /// re-baseline every number instead of catching a port bug.
    func testGeneratorIsThePinnedReferenceVersion() throws {
        let g = try loadGolden()
        XCTAssertEqual(g.generator, "adaptive_engine.js v2.27.0",
                       "golden.json regenerated from an unexpected reference version")
    }

    func testPatternOrderMatchesReference() throws {
        let g = try loadGolden()
        XCTAssertEqual(g.patternOrder, Pattern.ordered.map(\.rawValue),
                       "pattern order diverged from the reference")
    }

    /// The snapshot a break writes: the silent decay and the comeback record
    /// the same fields, so one assertion covers both.
    private struct BreakSnapshot {
        let levels: [Int]
        let streaks: [Int]
        let barLevel: Int?
        let barStreak: Int?
        let lessRun: Int?
        // A break moves the whole TRIPLE.
        let sub: [Int]?
        let cut: [Int]?
        let barCut: Int?
        // The hold on a returning set — the surviving per-pattern counter, and
        // the one the handles' snapshot carries.
        let setsHold: [Int]?
    }

    private func assertBreak(_ state: EngineState, _ snap: BreakSnapshot,
                             order: [String], ctx: String) {
        XCTAssertEqual(order.map { state.levels[Pattern(rawValue: $0)!] ?? -1 },
                       snap.levels, "\(ctx): levels")
        XCTAssertEqual(order.map { state.failStreak[Pattern(rawValue: $0)!] ?? -1 },
                       snap.streaks, "\(ctx): streaks")
        if let v = snap.barLevel { XCTAssertEqual(state.levels[.pullBar], v, "\(ctx): bar level") }
        if let v = snap.barStreak { XCTAssertEqual(state.failStreak[.pullBar], v, "\(ctx): bar streak") }
        if let v = snap.lessRun { XCTAssertEqual(state.lessRun, v, "\(ctx): less run") }
        // The decay steps along the growth path, so the sub-step and the cut
        // are part of where it landed.
        if let v = snap.sub {
            XCTAssertEqual(order.map { state.sub[Pattern(rawValue: $0)!] ?? 0 }, v,
                           "\(ctx): sub")
        }
        if let v = snap.cut {
            XCTAssertEqual(order.map { state.cut[Pattern(rawValue: $0)!] ?? 0 }, v,
                           "\(ctx): cut")
        }
        if let v = snap.barCut { XCTAssertEqual(state.cutOf(.pullBar), v, "\(ctx): bar cut") }
        if let v = snap.setsHold {
            XCTAssertEqual(order.map { state.setsHold[Pattern(rawValue: $0)!] ?? 0 }, v,
                           "\(ctx): sets hold")
        }
    }

    func testAllScenariosMatchReferenceEngine() throws {
        let g = try loadGolden()
        for scenario in g.scenarios {
            var state = EngineState.initial
            if let seed = scenario.seed {
                state.counter = seed.counter
                state.hasBar = seed.hasBar
                for (idx, name) in g.patternOrder.enumerated() {
                    let p = try XCTUnwrap(Pattern(rawValue: name))
                    state.levels[p] = seed.levels[idx]
                    state.failStreak[p] = seed.failStreak[idx]
                }
                state.levels[.pullBar] = seed.barLevel
                state.failStreak[.pullBar] = seed.barStreak
            }

            for (i, step) in scenario.steps.enumerated() {
                let ctx = "\(scenario.name)/step \(i + 1)"
                // The one settings toggle a scenario may flip between sessions
                // (: the budget was the second, and it is gone).
                state.hasBar = step.hasBar ?? state.hasBar
                replayBreaks(step, into: &state, order: g.patternOrder, ctx: ctx)
                replayHandles(step, into: &state, order: g.patternOrder, ctx: ctx)
                let session = Engine.generateSession(state)

                // --- session matches the reference ---
                XCTAssertEqual(session.sessionNumber, step.sessionNumber, ctx)
                XCTAssertEqual(session.estimatedTotalMin, step.estimatedTotalMin,
                               accuracy: 0.051, ctx + " (duration)")
                XCTAssertEqual(session.exercises.count, step.exercises.count, ctx)

                for (ex, ref) in zip(session.exercises, step.exercises) {
                    XCTAssertEqual(ex.pattern.rawValue, ref.pattern, ctx)
                    XCTAssertEqual(ex.tier, ref.tier, ctx + " \(ref.pattern) tier")
                    XCTAssertEqual(ex.unit.rawValue, ref.unit, ctx)
                    XCTAssertEqual(ex.load, ref.load, ctx + " \(ref.pattern) load")
                    XCTAssertEqual(ex.perSide, ref.perSide, ctx)
                    XCTAssertEqual(ex.sets, ref.sets, ctx)
                    XCTAssertEqual(ex.restSetSec, ref.restSetSec, ctx)
                    XCTAssertEqual(ex.restExerciseSec, ref.restExerciseSec, ctx)
                    // The per-set doses, absence included — a uniform plan
                    // must stay nil on both sides.
                    XCTAssertEqual(ex.loads, ref.loads, ctx + " \(ref.pattern) loads")
                }

                // --- feedback yields the same levels ---
                state = replayFeedback(step, from: state, session: session, ctx: ctx)

                let levels = Pattern.ordered.map { state.levels[$0]! }
                let streaks = Pattern.ordered.map { state.failStreak[$0]! }
                XCTAssertEqual(levels, step.levelsAfter, ctx + " (levels)")
                XCTAssertEqual(streaks, step.failStreakAfter, ctx + " (failStreak)")
                // The level is only half the position.
                if let subs = step.subAfter {
                    XCTAssertEqual(Pattern.ordered.map { state.sub[$0] ?? 0 }, subs,
                                   ctx + " (sub)")
                }
                if let barSub = step.barSubAfter {
                    XCTAssertEqual(state.sub[.pullBar] ?? 0, barSub, ctx + " (bar sub)")
                }

                // vertical branch snapshot
                if let barLevel = step.barLevelAfter {
                    XCTAssertEqual(state.levels[.pullBar], barLevel, ctx + " (bar level)")
                }
                if let barStreak = step.barStreakAfter {
                    XCTAssertEqual(state.failStreak[.pullBar], barStreak, ctx + " (bar streak)")
                }

                assertAuxFields(step, state, ctx: ctx)
            }
        }
    }

    /// The handles a step may carry, applied where the app applies them —
    /// after any break, before the plan is generated.
    ///
    /// The ORDER inside a step is part of the contract and is fixed here to
    /// match the reference: the easier-variation handle first (it changes the
    /// variation and zeroes both other coordinates), then a per-movement cut.
    /// Running them the other way round would let the first erase the second's
    /// work. v2.27 removed a third, session-wide handle from the end.
    ///
    /// `setCut` is walked in sorted key order for the same reason the chronic
    /// aim is walked in session order: a Swift Dictionary has none, and the
    /// reference's object literal does.
    private func replayHandles(_ step: Golden.Step, into state: inout EngineState,
                               order: [String], ctx: String) {
        guard let h = step.handles else { return }
        for raw in h.easierVariation ?? [] {
            state = Engine.easierVariation(state: state, pattern: Pattern(rawValue: raw)!)
        }
        for (raw, value) in (h.setCut ?? [:]).sorted(by: { $0.key < $1.key }) {
            state = Engine.setCut(state: state, pattern: Pattern(rawValue: raw)!, cut: value)
        }
        guard let levels = h.levelsAfter, let streaks = h.failStreakAfter else { return }
        assertBreak(state, BreakSnapshot(
            levels: levels, streaks: streaks,
            barLevel: h.barLevelAfter, barStreak: nil,
            lessRun: h.lessRunAfter,
            sub: h.subAfter, cut: h.cutAfter, barCut: h.barCutAfter,
            setsHold: h.setsHoldAfter),
            order: order, ctx: "\(ctx) handles")
    }

    /// The feedback of one step, and the sets skipped while doing it.
    ///
    /// v2.27 (§38.2, rule 1): a skip lands through the entry point that owns
    /// the order, so this replay cannot get it wrong even by accident. A step
    /// without `skipSets` goes through the plain call, so every pre-v2.27 step
    /// stays byte-for-byte what it was.
    ///
    /// SIX arguments on that plain call. Every optional is passed explicitly —
    /// the rule of the wave, kept because a default silently shifting is
    /// exactly what broke 480 cells out of 480 last time, and what the arity
    /// change would do again to a caller that was not updated.
    private func replayFeedback(_ step: Golden.Step, from state: EngineState,
                                session: Session, ctx: String) -> EngineState {
        let result = FeedbackResult(rawValue: step.result)!
        let overrides = Dictionary(uniqueKeysWithValues:
            step.overrides.map { (Pattern(rawValue: $0.key)!, $0.value) })
        let skipped = Set((step.skipped ?? []).map { Pattern(rawValue: $0)! })
        let setsSkipped = Dictionary(uniqueKeysWithValues:
            (step.skipSets ?? [:]).map { (Pattern(rawValue: $0.key)!, $0.value) })
        guard !setsSkipped.isEmpty else {
            return Engine.applyFeedback(state: state, session: session, result: result,
                                        overrides: overrides, skipped: skipped,
                                        gapDays: step.gapDays)
        }
        // The cut BEFORE the skip is asserted first: it is the one number that
        // separates "fed back, then skipped" from "skipped, then fed back",
        // and without it the fixture would pin the destination while leaving
        // the road open.
        if let before = step.cutBeforeSkip {
            let feedbackOnly = Engine.applyFeedback(
                state: state, session: session, result: result,
                overrides: overrides, skipped: skipped, gapDays: step.gapDays)
            XCTAssertEqual(Pattern.ordered.map { feedbackOnly.cutOf($0) }, before,
                           ctx + " (cut before the skip)")
        }
        return Engine.applyFeedback(state: state, session: session, result: result,
                                    overrides: overrides, skipped: skipped,
                                    setsSkipped: setsSkipped, gapDays: step.gapDays)
    }

    /// The breaks a step may carry, replayed in the app's order: the silent
    /// decay first, then the comeback (: possibly a series of them with no
    /// session between).: the "I was sick" tap was the third and is gone with
    /// the lens.
    private func replayBreaks(_ step: Golden.Step, into state: inout EngineState,
                              order: [String], ctx: String) {
        if let decay = step.silentDecay {
            state = Engine.applySilentDecay(state: state, gapDays: decay.gapDays)
            assertBreak(state, BreakSnapshot(
                levels: decay.levelsAfter, streaks: decay.failStreakAfter,
                barLevel: decay.barLevelAfter, barStreak: decay.barStreakAfter,
                lessRun: decay.lessRunAfter,
                sub: decay.subAfter, cut: decay.cutAfter, barCut: decay.barCutAfter,
                setsHold: decay.setsHoldAfter),
                order: order, ctx: "\(ctx) silent decay")
            if let hist = decay.lessHistAfter {
                var actual: [String: Int] = [:]
                for (p, mask) in state.lessHist where mask > 0 { actual[p.rawValue] = mask }
                XCTAssertEqual(actual, hist, "\(ctx) decay (appearance window)")
            }
            if let run = decay.returnRunAfter {
                XCTAssertEqual(state.returnRun, run, "\(ctx) decay (return run)")
            }
        }
        for (n, comeback) in (step.comeback?.snaps ?? []).enumerated() {
            state = Engine.applyComeback(state: state, gapDays: comeback.gapDays,
                                         alreadyDecayed: comeback.alreadyDecayed ?? false)
            let cctx = "\(ctx) comeback[\(n)]"
            assertBreak(state, BreakSnapshot(
                levels: comeback.levelsAfter, streaks: comeback.failStreakAfter,
                barLevel: comeback.barLevelAfter, barStreak: comeback.barStreakAfter,
                lessRun: comeback.lessRunAfter,
                sub: comeback.subAfter, cut: comeback.cutAfter,
                barCut: comeback.barCutAfter, setsHold: comeback.setsHoldAfter),
                order: order, ctx: cctx)
            XCTAssertEqual(state.counter, comeback.counterAfter,
                           "\(cctx) must not move the counter")
            if let hist = comeback.lessHistAfter {
                var actual: [String: Int] = [:]
                for (p, mask) in state.lessHist where mask > 0 { actual[p.rawValue] = mask }
                XCTAssertEqual(actual, hist, "\(cctx) (appearance window)")
            }
            if let run = comeback.returnRunAfter {
                XCTAssertEqual(state.returnRun, run, "\(cctx) (return run)")
            }
        }
    }

    /// The sets handle and everything the wave put in the state around it —
    /// the third coordinate of a position, the memory of pain, the hold on a
    /// returning set, the shown-plan memory, and the three -28.5 fields that
    /// used to sit outside the golden contract altogether. Split out of
    /// `assertAuxFields` so that function keeps its complexity budget.
    private func assertSetsHandle(_ step: Golden.Step, _ state: EngineState, ctx: String) {
        if let cut = step.cutAfter {
            XCTAssertEqual(Pattern.ordered.map { state.cut[$0] ?? 0 }, cut, ctx + " (cut)")
        }
        if let v = step.barCutAfter { XCTAssertEqual(state.cutOf(.pullBar), v, ctx + " (bar cut)") }
        if let v = step.setsHoldAfter {
            XCTAssertEqual(Pattern.ordered.map { state.setsHold[$0] ?? 0 }, v,
                           ctx + " (sets hold)")
        }
        if let v = step.barSetsHoldAfter {
            XCTAssertEqual(state.setsHold[.pullBar] ?? 0, v, ctx + " (bar sets hold)")
        }
        if let v = step.shownWorkAfter {
            XCTAssertEqual(Pattern.ordered.map { state.shownWork[$0] ?? 0 }, v,
                           ctx + " (shown work)")
        }
        if let v = step.barShownWorkAfter {
            XCTAssertEqual(state.shownWork[.pullBar] ?? 0, v, ctx + " (bar shown work)")
        }
        if let v = step.shownOrdAfter {
            XCTAssertEqual(Pattern.ordered.map { state.shownOrd[$0] ?? 0 }, v,
                           ctx + " (shown position)")
        }
        if let v = step.barShownOrdAfter {
            XCTAssertEqual(state.shownOrd[.pullBar] ?? 0, v, ctx + " (bar shown position)")
        }
        // The three fields that were outside the contract until then.
        if let v = step.rampWindowAfter {
            XCTAssertEqual(state.rampWindow, v, ctx + " (ramp window)")
        }
        if let v = step.weekGainAfter {
            XCTAssertEqual(Pattern.ordered.map { state.weekGain[$0] ?? 0 }, v,
                           ctx + " (weekly gain)")
        }
        if let v = step.barWeekGainAfter {
            XCTAssertEqual(state.weekGain[.pullBar] ?? 0, v, ctx + " (bar weekly gain)")
        }
        if let v = step.weekAgeDaysAfter {
            XCTAssertEqual(state.weekAgeDays, v, accuracy: 1e-9, ctx + " (window age)")
        }
    }

    /// Every optional per-step snapshot past levels and streaks — the fields
    /// each wave added, compared only where the fixture carries them.
    private func assertAuxFields(_ step: Golden.Step, _ state: EngineState, ctx: String) {
        assertSetsHandle(step, state, ctx: ctx)         //
        // The run of unnamed "less" ratings
        if let lessRun = step.lessRunAfter {
            XCTAssertEqual(state.lessRun, lessRun, ctx + " (less run)")
        }
        // The window of recent appearances
        if let hist = step.lessHistAfter {
            var actual: [String: Int] = [:]
            for (p, mask) in state.lessHist where mask > 0 { actual[p.rawValue] = mask }
            XCTAssertEqual(actual, hist, ctx + " (appearance window)")
        }
        // The cross-credit pause on the pull slot
        if let paused = step.creditPausedAfter {
            XCTAssertEqual([Pattern.pull, .pullBar].map { state.creditPaused.contains($0) ? 1 : 0 },
                           paused, ctx + " (credit paused)")
        }
        // The comeback series. The lens was the other half of and is gone.
        if let run = step.returnRunAfter {
            XCTAssertEqual(state.returnRun, run, ctx + " (return run)")
        }
    }
}
