//
//  Library.swift
//  DredfitCore
//
//  GENERATED by gen_content.js — do not edit by hand.
//  Library: 9 patterns × 3 tiers. Base language English, translation Russian
//  (Resources/Localizable.xcstrings). Technique: 3 steps + 2 common mistakes.
//

import Foundation

public struct ExerciseVariation: Equatable, Sendable {
    public let name: String
    public let unilateral: Bool
    public let steps: [String]
    public let mistakes: [String]
}

public struct ExerciseEntry: Equatable, Sendable {
    public let pattern: Pattern
    public let unit: LoadUnit
    public let variations: [ExerciseVariation]  // index = tier − 1
}

public enum ExerciseLibrary {

    public static func entry(for pattern: Pattern) -> ExerciseEntry {
        entries[pattern]!
    }

    public static let entries: [Pattern: ExerciseEntry] = [

        .squat: ExerciseEntry(pattern: .squat, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Squat", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Feet shoulder-width apart, toes slightly out, weight over the whole foot.", bundle: .module),
                    String(localized: "Sit back and down for ~2 seconds; knees track over the toes, back straight.", bundle: .module),
                    String(localized: "Thighs parallel to the floor at the bottom; drive up on an exhale.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Knees caving inward — keep them tracking over your feet.", bundle: .module),
                    String(localized: "Heels lifting off the floor — depth matters more than speed.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Bulgarian split squat", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Rear foot on a chair or couch behind you, front foot a stride ahead.", bundle: .module),
                    String(localized: "Lower straight down until the rear knee almost touches the floor.", bundle: .module),
                    String(localized: "Drive up through the front heel; torso leaning slightly forward.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Stance too short — the front knee travels far past the toes.", bundle: .module),
                    String(localized: "Loading the rear leg — it is only there for balance.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Pistol squat", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Stand on one leg, the other extended forward, arms out for balance.", bundle: .module),
                    String(localized: "Lower slowly until the hamstring rests on the calf, heel on the floor.", bundle: .module),
                    String(localized: "Stand up without your hands; start with a doorframe assist if needed.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Dropping down without control — the descent must be slow.", bundle: .module),
                    String(localized: "Knee drifting sideways — keep it tracking over the foot.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Shrimp squat", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Stand on one leg; bend the other back and hold its foot with one hand.", bundle: .module),
                    String(localized: "Lower slowly until the back knee gently touches the floor.", bundle: .module),
                    String(localized: "Stand up through the heel of the working leg, chest up.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Knee crashing into the floor — the descent stays slow and controlled.", bundle: .module),
                    String(localized: "Leaning far forward — keep the chest up and the core braced.", bundle: .module),
                ]),
        ]),

        .pushH: ExerciseEntry(pattern: .pushH, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Knee push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Hands under the shoulders, knees on the floor; head to knees form a straight line.", bundle: .module),
                    String(localized: "Lower for ~2 seconds until the chest nearly touches the floor, elbows about 45° from the torso.", bundle: .module),
                    String(localized: "Press up on an exhale, keeping the belly tight.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Sagging hips — squeeze your glutes and abs.", bundle: .module),
                    String(localized: "Cutting the range short — the chest should almost touch the floor.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Hands under the shoulders; the body is one straight line from head to heels.", bundle: .module),
                    String(localized: "Lower for ~2 seconds until the chest nearly touches the floor, elbows about 45° from the torso.", bundle: .module),
                    String(localized: "Press up on an exhale; don't fully lock the elbows at the top.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Sagging hips or a raised butt — the core stops working.", bundle: .module),
                    String(localized: "Elbows flared out to 90° — this overloads the shoulders.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Feet-elevated push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Feet on a chair or couch, hands under the shoulders on the floor.", bundle: .module),
                    String(localized: "Keep the body rigid and lower until the chest nearly touches the floor.", bundle: .module),
                    String(localized: "The higher the support, the harder it gets — start low.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Lower back arching — don't let the hips sag.", bundle: .module),
                    String(localized: "Leading with the head — keep the neck in line with the torso.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Archer push-up", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Take a wide hand position; the body stays one straight line.", bundle: .module),
                    String(localized: "Lower toward one hand, bending that elbow; the other arm stays straight.", bundle: .module),
                    String(localized: "Press up and repeat to the same side for the whole set, then switch.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips rotating — shoulders and hips stay square to the floor.", bundle: .module),
                    String(localized: "Half range — the chest goes down to the working hand.", bundle: .module),
                ]),
        ]),

        .hinge: ExerciseEntry(pattern: .hinge, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Glute bridge", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Lie on your back, feet close to the glutes hip-width apart, arms at your sides.", bundle: .module),
                    String(localized: "Lift the hips until knees, hips and shoulders form one straight line.", bundle: .module),
                    String(localized: "Squeeze the glutes for a second at the top, then lower slowly without touching the floor.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Arching the lower back — don't push past the straight line.", bundle: .module),
                    String(localized: "Pushing through the toes — keep the weight on the heels.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Single-leg glute bridge", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Lie on your back, one foot near the glutes, the other leg extended.", bundle: .module),
                    String(localized: "Lift the hips with one leg to a straight line, keeping the pelvis level.", bundle: .module),
                    String(localized: "Pause a second at the top, lower slowly.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Pelvis tilting sideways — keep both hip bones pointing at the ceiling.", bundle: .module),
                    String(localized: "Helping with the free leg — it stays out of the movement.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Single-leg Romanian deadlift", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Stand on one leg with a soft knee; hinge forward from the hips with a flat back.", bundle: .module),
                    String(localized: "The free leg extends back; torso and leg form one line, hands reaching toward the floor.", bundle: .module),
                    String(localized: "Stand back up by squeezing the glute of the standing leg.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Rounding the back — keep the shoulder blades set, hinge from the hips.", bundle: .module),
                    String(localized: "Pelvis rotating open — keep the hips square to the floor.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Sliding leg curl", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Lie on your back, heels on a towel on a smooth floor, hips lifted.", bundle: .module),
                    String(localized: "Slide the heels away until the legs are almost straight, hips stay up.", bundle: .module),
                    String(localized: "Pull the heels back toward the glutes — that's one rep.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips dropping as the legs extend — keep the bridge the whole time.", bundle: .module),
                    String(localized: "Jerky pulls — slide out and back slowly, with control.", bundle: .module),
                ]),
        ]),

        .pull: ExerciseEntry(pattern: .pull, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Y-T-W raises", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Lie face down, forehead near the floor, arms extended in a Y shape.", bundle: .module),
                    String(localized: "Lift the straight arms for 2 seconds, squeezing the shoulder blades, then lower.", bundle: .module),
                    String(localized: "Repeat in a T position and a W position — together that's one rep.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Jerking the torso up — only the arms and shoulder blades lift.", bundle: .module),
                    String(localized: "Shoulders creeping toward the ears — pull the blades down and back.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Inverted row (table)", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Lie under a sturdy table and grab the edge with a shoulder-width grip.", bundle: .module),
                    String(localized: "Body straight from shoulders to heels; pull the chest to the edge, squeezing the shoulder blades.", bundle: .module),
                    String(localized: "Lower slowly until the arms are straight.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Sagging hips — hold the body like a plank.", bundle: .module),
                    String(localized: "Pulling only with the arms — start by squeezing the shoulder blades.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Feet-elevated inverted row", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Same setup, but feet up on a chair — the body is parallel to the floor.", bundle: .module),
                    String(localized: "Pull the chest to the table edge with a rigid torso.", bundle: .module),
                    String(localized: "Pause a second at the top; lower under control.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Reaching with the chin instead of the chest — lead with the chest.", bundle: .module),
                    String(localized: "Rushing the reps — control both directions.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Archer inverted row", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Set up under the table with a wide grip, body straight.", bundle: .module),
                    String(localized: "Pull the chest toward one hand; the other arm stays nearly straight.", bundle: .module),
                    String(localized: "Lower under control; whole set to one side, then switch.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips sagging — hold the plank line through the set.", bundle: .module),
                    String(localized: "Both arms pulling equally — the working arm does the job.", bundle: .module),
                ]),
        ]),

        .pushV: ExerciseEntry(pattern: .pushV, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Wall push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Stand a step away from a wall, palms on it slightly wider than shoulders, at chest height.", bundle: .module),
                    String(localized: "Bend the elbows, bringing the face toward the wall, body in one line.", bundle: .module),
                    String(localized: "Push back to straight arms; the farther the feet, the harder.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips dropping back — the whole body moves as one line.", bundle: .module),
                    String(localized: "Elbows flared to 90° — keep them closer to the torso.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Pike push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "From a push-up position, lift the hips high — the body forms an inverted V.", bundle: .module),
                    String(localized: "Bend the elbows, lowering the top of the head toward the floor between the hands.", bundle: .module),
                    String(localized: "Press back up without dropping the hips.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips dropping as the arms bend — keep the V shape.", bundle: .module),
                    String(localized: "Bumping the head on the floor — lower slowly, with control.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Wall handstand push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Kick up into a handstand with your back to the wall, heels resting on it.", bundle: .module),
                    String(localized: "Bend the elbows slowly, lowering the top of the head toward the floor.", bundle: .module),
                    String(localized: "Press back up; know how to exit safely — step down one leg at a time.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Arching the lower back — keep the core and glutes tight.", bundle: .module),
                    String(localized: "Elbows drifting outward — track them forward and down.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Chest-to-wall handstand push-up", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Walk your feet up the wall, chest facing it, body close to vertical.", bundle: .module),
                    String(localized: "Bend the elbows slowly, lowering the head to the floor.", bundle: .module),
                    String(localized: "Press back up; keep the body in one tight line.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Arching away from the wall — stay close, ribs tucked in.", bundle: .module),
                    String(localized: "Uncontrolled descent — the head must land softly.", bundle: .module),
                ]),
        ]),

        .lunge: ExerciseEntry(pattern: .lunge, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Static lunge", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Step into a lunge stance and stay in it for the whole set.", bundle: .module),
                    String(localized: "Lower straight down until the rear knee almost touches the floor.", bundle: .module),
                    String(localized: "Drive up through the front heel, torso upright.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Front knee traveling far past the toes — take a longer stance.", bundle: .module),
                    String(localized: "Torso tipping forward — keep the chest up.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Reverse lunge", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "From standing, step back and lower the rear knee almost to the floor.", bundle: .module),
                    String(localized: "The front shin stays near vertical; weight on the front heel.", bundle: .module),
                    String(localized: "Push off and return to standing — that's one rep.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Too short a step back — the front knee gets overloaded.", bundle: .module),
                    String(localized: "Losing balance — fix your eyes on a point ahead.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Jump lunge", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "From a lunge, jump up and switch legs in the air.", bundle: .module),
                    String(localized: "Land softly in a lunge on the other side, knee almost to the floor.", bundle: .module),
                    String(localized: "Keep a steady rhythm; use the arms for balance.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Landing stiff on a straight leg — absorb by bending.", bundle: .module),
                    String(localized: "Knee slamming into the floor — control the depth.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Paused jump lunge", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Jump and switch legs in the air, landing softly in a lunge.", bundle: .module),
                    String(localized: "Hold the bottom position for a full 2 seconds, knee near the floor.", bundle: .module),
                    String(localized: "Explode up into the next switch — pause every landing.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Skipping the pause — hold an honest 2 seconds at the bottom.", bundle: .module),
                    String(localized: "Shallow landings — the knee comes close to the floor each rep.", bundle: .module),
                ]),
        ]),

        .coreAntiExt: ExerciseEntry(pattern: .coreAntiExt, unit: .hold, variations: [
            ExerciseVariation(
                name: String(localized: "Knee plank", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Forearms on the floor, elbows under the shoulders, knees down.", bundle: .module),
                    String(localized: "Head to knees — one straight line; belly pulled in.", bundle: .module),
                    String(localized: "Breathe steadily and hold for the planned time.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips sagging — tuck the pelvis slightly.", bundle: .module),
                    String(localized: "Shoulders at the ears — push the floor away, keep the neck long.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Plank", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Forearms on the floor, elbows under the shoulders, feet hip-width.", bundle: .module),
                    String(localized: "One straight line from head to heels; glutes and abs braced.", bundle: .module),
                    String(localized: "Breathe steadily; shaking is fine, a sagging line is not.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips hiked up — easier, but pointless.", bundle: .module),
                    String(localized: "Lower back sagging — that strains the spine; better to stop early.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Hollow hold", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Lie on your back, press the lower back into the floor, arms extended overhead.", bundle: .module),
                    String(localized: "Lift the shoulder blades and straight legs 15–20 cm off the floor.", bundle: .module),
                    String(localized: "Hold the shape with the lower back pressed down the whole time.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Lower back lifting off the floor — raise the legs higher or bend the knees.", bundle: .module),
                    String(localized: "Holding your breath — keep breathing shallow and steady.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Long-lever plank", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Take a plank on the forearms, elbows well ahead of the shoulders.", bundle: .module),
                    String(localized: "Keep one straight line from head to heels, glutes tight.", bundle: .module),
                    String(localized: "The farther the elbows, the harder — breathe steadily and hold.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips sagging — tuck the pelvis and brace the abs.", bundle: .module),
                    String(localized: "Elbows too far too soon — increase the lever gradually.", bundle: .module),
                ]),
        ]),

        .coreRot: ExerciseEntry(pattern: .coreRot, unit: .hold, variations: [
            ExerciseVariation(
                name: String(localized: "Bird dog (hold)", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "On all fours: hands under the shoulders, knees under the hips.", bundle: .module),
                    String(localized: "Extend the opposite arm and leg into one line with the torso.", bundle: .module),
                    String(localized: "Hold without wobbling; pelvis and shoulders stay level.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Lower back arching as the leg lifts — the leg goes no higher than the torso.", bundle: .module),
                    String(localized: "Torso rotating — imagine a glass of water on your lower back.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Side plank", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Lie on your side, elbow under the shoulder, feet stacked.", bundle: .module),
                    String(localized: "Lift the hips until feet–hips–shoulders form a straight line.", bundle: .module),
                    String(localized: "Hold without letting the hips drop; free hand on the waist or up.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips sagging — keep the body line straight.", bundle: .module),
                    String(localized: "Torso tipping forward — shoulders and hips in one plane.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Side plank with leg raise", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Get into a side plank on the elbow.", bundle: .module),
                    String(localized: "Raise the top leg 20–30 cm and hold it straight.", bundle: .module),
                    String(localized: "Hips high, the body in one plane.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips dropping when the leg lifts — stabilize the plank first.", bundle: .module),
                    String(localized: "Leg drifting forward — keep it in line with the torso.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Star side plank", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "From a side plank, raise the top leg and the top arm at once.", bundle: .module),
                    String(localized: "The body forms a star: straight line plus raised limbs.", bundle: .module),
                    String(localized: "Hips high the whole hold; look straight ahead.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Hips dropping — the base line comes first, the star second.", bundle: .module),
                    String(localized: "Body folding forward — shoulders, hips and legs in one plane.", bundle: .module),
                ]),
        ]),

        .calf: ExerciseEntry(pattern: .calf, unit: .reps, variations: [
            ExerciseVariation(
                name: String(localized: "Calf raises", bundle: .module),
                unilateral: false,
                steps: [
                    String(localized: "Stand with feet hip-width; hand on a wall for balance.", bundle: .module),
                    String(localized: "Rise as high as you can onto the balls of the feet, pause a second at the top.", bundle: .module),
                    String(localized: "Lower slowly; for more range, stand with the toes on a step edge.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Fast bouncing — move slowly with a pause at the top.", bundle: .module),
                    String(localized: "Cutting the range — rise all the way up.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Single-leg calf raise", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Stand on one leg, hand on a wall for balance.", bundle: .module),
                    String(localized: "Rise onto the ball of the foot as high as possible, pause for a second.", bundle: .module),
                    String(localized: "Lower slowly, heel to the floor (or below step level).", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Helping with the other leg — it stays off the floor.", bundle: .module),
                    String(localized: "Ankle rolling outward — press through the big toe.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Single-leg calf raise with pause", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Same as the single-leg raise, but with a 3-second pause at the top.", bundle: .module),
                    String(localized: "Up in 1 second, hold for 3, down for 3.", bundle: .module),
                    String(localized: "Full range beats rep count.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Skipping the pause — hold an honest 3 seconds at the top.", bundle: .module),
                    String(localized: "Knee bending — the leg stays straight; only the ankle works.", bundle: .module),
                ]),
            ExerciseVariation(
                name: String(localized: "Single-leg calf raise on a step", bundle: .module),
                unilateral: true,
                steps: [
                    String(localized: "Stand on one leg with the ball of the foot on a step edge.", bundle: .module),
                    String(localized: "Lower the heel below the step level, feel the stretch.", bundle: .module),
                    String(localized: "Rise as high as possible, pause a second, lower for 3 seconds.", bundle: .module),
                ],
                mistakes: [
                    String(localized: "Short bottom range — the heel must drop below the step.", bundle: .module),
                    String(localized: "Bouncing out of the stretch — pause briefly at the bottom too.", bundle: .module),
                ]),
        ]),
    ]
}
