//
//  Cross-check of the Kotlin port against the reference JS engine — the port
//  of GoldenTests.swift.
//
//  golden.json is generated by make_golden.js from the pinned reference
//  adaptive_engine.js: a full snapshot of every session and of the state after
//  every feedback step, per scenario. Scenarios may start from a seeded state,
//  may apply a decay and a series of comebacks, and may pull handles before
//  the plan — all replayed here exactly as the app would.
//
//  A divergence in even one number = a port error. The judge is the fixture,
//  not the Swift port. Do not edit the fixture by hand.
//

package com.dredfit.core

import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.test.fail

class GoldenTest {

    private val golden: Golden by lazy { Golden.load() }

    /** The fixture must come from the pinned reference version. */
    @Test
    fun generatorIsThePinnedReferenceVersion() {
        assertEquals("adaptive_engine.js v3.8.0", golden.generator,
                     "golden.json regenerated from an unexpected reference version")
    }

    /** TEN patterns, in one order for everything: the reference's `ALL_PATTERNS`. */
    @Test
    fun patternOrderMatchesReference() {
        assertEquals(Pattern.allCases.map { it.rawValue }, golden.patternOrder,
                     "pattern order diverged from the reference")
    }

    /** The dose grids, compared with the fixture rather than retyped. */
    @Test
    fun doseGridsMatchReference() {
        for ((name, grid) in golden.dose) {
            val unit = assertNotNull(LoadUnit.fromRaw(name))
            assertEquals(grid.min, Dose.grid(unit).min, "$name floor")
            assertEquals(grid.max, Dose.grid(unit).max, "$name ceiling")
            assertEquals(grid.step, Dose.grid(unit).step, "$name step")
        }
        assertEquals(setOf("reps", "hold"), golden.dose.keys)
    }

    /** The ladders themselves: length, difficulty, unit, sides, and the one
     *  probe-only boundary. Names are NOT compared — the fixture carries the
     *  Russian reference text; LibraryPinTest pins the identities. */
    @Test
    fun laddersMatchReference() {
        assertEquals(59, golden.library.values.sumOf { it.size }, "59 positions across ten ladders")
        for (p in Pattern.allCases) {
            val rungs = assertNotNull(golden.library[p.rawValue], "${p.rawValue} missing from the fixture")
            val entry = ExerciseLibrary.entry(p)
            assertEquals(rungs.size, entry.count, "${p.rawValue}: ladder length")
            for ((i, rung) in rungs.withIndex()) {
                val v = i + 1
                val mine = entry.variation(v)
                assertEquals(rung.w, mine.w, 1e-12, "${p.rawValue} v$v: w")
                assertEquals(rung.unit, mine.unit.rawValue, "${p.rawValue} v$v: unit")
                assertEquals(rung.perSide, mine.unilateral, "${p.rawValue} v$v: sides")
                assertEquals(rung.probeOnly ?: false, entry.probeOnly(variation = v),
                             "${p.rawValue} v$v: probe-only boundary")
            }
        }
    }

    @Test
    fun allScenariosMatchReferenceEngine() {
        val order = golden.patternOrder.map { assertNotNull(Pattern.fromRaw(it)) }
        for (scenario in golden.scenarios) {
            var state = seedState(scenario.seed, order)
            for ((i, step) in scenario.steps.withIndex()) {
                val ctx = "${scenario.name}/step ${i + 1}"
                // The one settings toggle a scenario may flip between sessions.
                state.hasBar = step.hasBar ?: state.hasBar
                state = replayBreaks(step, state, order, ctx)
                state = replayHandles(step, state, order, ctx)

                val session = Engine.generateSession(state)
                assertSession(session, step, ctx)

                state = replayFeedback(step, state, session, order, ctx)
                assertState(state, step.snapshot, order, ctx)
                assertGlobals(state, step, ctx)
            }
        }
    }

    // MARK: - Replay

    private fun seedState(seed: Golden.Seed?, order: List<Pattern>): EngineState {
        val state = EngineState.initial
        if (seed == null) return state
        state.counter = seed.counter
        state.hasBar = seed.hasBar
        for ((idx, p) in order.withIndex()) {
            state.vars[p] = seed.vars[idx]
            state.doses[p] = seed.doses[idx]
            state.failStreak[p] = seed.failStreak[idx]
            if (seed.sets[idx] != EngineConfig.setsBase) state.sets[p] = seed.sets[idx]
            if (seed.sub[idx] > 0) state.sub[p] = seed.sub[idx]
            if (seed.cut[idx] > 0) state.cut[p] = seed.cut[idx]
            if (seed.lastHard[idx] == 1) state.lastHard.add(p)
        }
        state.shown = decodeShown(seed.shown)
        state.shownWork = patternKeyed(seed.shownWork ?: emptyMap())
        state.shownOrd = patternKeyed(seed.shownOrd ?: emptyMap())
        return state
    }

    /** The breaks a step may carry, replayed in the app's order: the silent
     *  decay first, then the comeback (possibly a series). */
    private fun replayBreaks(step: Golden.Step, start: EngineState,
                             order: List<Pattern>, ctx: String): EngineState {
        var state = start
        step.silentDecay?.let { decay ->
            state = Engine.applySilentDecay(state = state, gapDays = decay.gapDays)
            assertState(state, decay.snapshot, order, "$ctx silent decay")
            assertStreaks(state, decay.failStreakAfter, order, "$ctx silent decay")
        }
        for ((n, comeback) in (step.comeback?.snaps ?: emptyList()).withIndex()) {
            state = Engine.applyComeback(state = state, gapDays = comeback.gapDays,
                                         alreadyDecayed = comeback.alreadyDecayed ?: false)
            val cctx = "$ctx comeback[$n]"
            assertState(state, comeback.snapshot, order, cctx)
            assertStreaks(state, comeback.failStreakAfter, order, cctx)
            assertEquals(comeback.counterAfter, state.counter, "$cctx must not move the counter")
            assertEquals(comeback.returnRunAfter, state.returnRun, "$cctx (return run)")
        }
        return state
    }

    /** Handles land after any break, before the plan: the easier-variation
     *  handle first, then a per-movement cut, walked in sorted key order. */
    private fun replayHandles(step: Golden.Step, start: EngineState,
                              order: List<Pattern>, ctx: String): EngineState {
        val h = step.handles ?: return start
        var state = start
        for (raw in h.easierVariation ?: emptyList()) {
            state = Engine.easierVariation(state = state, pattern = assertNotNull(Pattern.fromRaw(raw)))
        }
        for ((raw, value) in (h.setCut ?: emptyMap()).entries.sortedBy { it.key }) {
            state = Engine.setCut(state = state, pattern = assertNotNull(Pattern.fromRaw(raw)), cut = value)
        }
        assertState(state, h.snapshot, order, "$ctx handles")
        return state
    }

    /** The feedback of one step, and the sets skipped while doing it. SEVEN
     *  arguments on the plain call, every optional passed explicitly. */
    private fun replayFeedback(step: Golden.Step, state: EngineState, session: Session,
                               order: List<Pattern>, ctx: String): EngineState {
        val result = assertNotNull(FeedbackResult.fromRaw(step.result))
        val overrides = step.overrides.mapKeys { assertNotNull(Pattern.fromRaw(it.key)) }
        val probes = patternKeyed(step.probes ?: emptyMap())
        val skipped = (step.skipped ?: emptyList()).map { assertNotNull(Pattern.fromRaw(it)) }.toSet()
        val setsSkipped = patternKeyed(step.skipSets ?: emptyMap())
        val raised = patternKeyed(step.raiseDose ?: emptyMap())
        if (setsSkipped.isEmpty() && raised.isEmpty()) {
            return Engine.applyFeedback(state = state, session = session, result = result,
                                        overrides = overrides, skipped = skipped,
                                        gapDays = step.gapDays, probes = probes)
        }
        // The cut BEFORE the skip separates "fed back, then skipped" from
        // "skipped, then fed back".
        step.cutBeforeSkip?.let { before ->
            val feedbackOnly = Engine.applyFeedback(
                state = state, session = session, result = result, overrides = overrides,
                skipped = skipped, gapDays = step.gapDays, probes = probes)
            assertEquals(before, order.map { feedbackOnly.cutOf(it) }, "$ctx (cut before the skip)")
        }
        // The raise lands after the feedback AND after the skip.
        step.beforeRaise?.let { before ->
            val unraised = Engine.applyFeedback(
                state = state, session = session, result = result, overrides = overrides,
                skipped = skipped, setsSkipped = setsSkipped, gapDays = step.gapDays,
                probes = probes)
            assertEquals(before.doses, order.map { unraised.doses[it] }, "$ctx (dose before the raise)")
            assertEquals(before.sub, order.map { unraised.sub[it] ?: 0 }, "$ctx (sub-step before the raise)")
        }
        return Engine.applyFeedback(state = state, session = session, result = result,
                                    overrides = overrides, skipped = skipped,
                                    setsSkipped = setsSkipped, gapDays = step.gapDays,
                                    probes = probes, raised = raised)
    }

    // MARK: - Assertions

    private fun assertSession(session: Session, step: Golden.Step, ctx: String) {
        assertEquals(step.sessionNumber, session.sessionNumber, ctx)
        assertEquals(step.warmupMin, session.warmupMin, "$ctx (warm-up)")
        assertEquals(step.cooldownMin, session.cooldownMin, "$ctx (cool-down)")
        assertEquals(step.estimatedTotalMin, session.estimatedTotalMin, 0.051, "$ctx (duration)")
        assertEquals(step.exercises.size, session.exercises.size, ctx)
        for ((ex, ref) in session.exercises.zip(step.exercises)) {
            assertEquals(ref.pattern, ex.pattern.rawValue, ctx)
            assertEquals(ref.variation, ex.variation, "$ctx ${ref.pattern} variation")
            assertEquals(ref.unit, ex.unit.rawValue, "$ctx ${ref.pattern} unit")
            assertEquals(ref.load, ex.load, "$ctx ${ref.pattern} load")
            assertEquals(ref.perSide, ex.perSide, "$ctx ${ref.pattern} sides")
            assertEquals(ref.sets, ex.sets, "$ctx ${ref.pattern} sets")
            assertEquals(ref.restSetSec, ex.restSetSec, "$ctx ${ref.pattern} rest")
            assertEquals(ref.restExerciseSec, ex.restExerciseSec, ctx)
            // The per-set doses, absence included.
            assertEquals(ref.loads, ex.loads, "$ctx ${ref.pattern} loads")
            assertProbe(ex, ref, ctx)
        }
    }

    /** The probe, absence included. */
    private fun assertProbe(ex: SessionExercise, ref: Golden.Ex, ctx: String) {
        val refProbe = ref.probe
        if (refProbe == null) {
            assertNull(ex.probe, "$ctx ${ref.pattern} must carry no probe")
            return
        }
        val probe = ex.probe ?: fail("$ctx ${ref.pattern} must carry a probe")
        assertEquals(refProbe.variation, probe.variation, "$ctx ${ref.pattern} probe variation")
        assertEquals(refProbe.unit, probe.unit.rawValue, "$ctx ${ref.pattern} probe unit")
        assertEquals(refProbe.load, probe.load, "$ctx ${ref.pattern} probe load")
        assertEquals(refProbe.perSide, probe.perSide, "$ctx ${ref.pattern} probe sides")
    }

    /** Every coordinate of every position, plus the journal and the counters a
     *  snapshot carries — the same call for a step, a break and a handle pull. */
    private fun assertState(state: EngineState, snap: Golden.Snapshot, order: List<Pattern>, ctx: String) {
        assertEquals(snap.varsAfter, order.map { state.vars[it] ?: -1 }, "$ctx (vars)")
        assertEquals(snap.setsAfter, order.map { state.sets[it] ?: EngineConfig.setsBase }, "$ctx (sets)")
        assertEquals(snap.dosesAfter, order.map { state.doses[it] ?: -1 }, "$ctx (doses)")
        assertEquals(snap.subAfter, order.map { state.sub[it] ?: 0 }, "$ctx (sub)")
        assertEquals(snap.cutAfter, order.map { state.cutOf(it) }, "$ctx (cut)")
        assertEquals(snap.lastHardAfter, order.map { if (it in state.lastHard) 1 else 0 }, "$ctx (last hard)")
        assertEquals(snap.setsHoldAfter, order.map { state.setsHold[it] ?: 0 }, "$ctx (sets hold)")
        assertEquals(snap.shownWorkAfter, order.map { state.shownWork[it] ?: 0 }, "$ctx (shown work)")
        assertEquals(snap.shownOrdAfter, order.map { state.shownOrd[it] ?: 0 }, "$ctx (shown position)")
        assertEquals(snap.shownCapAfter, order.map { state.shownCap[it] ?: 0 }, "$ctx (pull cap shown under)")
        assertEquals(snap.shownOwnAfter, order.map { state.shownOwn[it] ?: 0 }, "$ctx (own sets shown with)")
        assertEquals(snap.shownSkipAfter, order.map { if (it in state.shownSkip) 1 else 0 },
                     "$ctx (a set taken off since)")
        assertEquals(snap.rampWindowAfter, state.rampWindow, "$ctx (ramp window)")
        assertEquals(snap.weekGainAfter, order.map { state.weekGain[it] ?: 0 }, "$ctx (weekly gain)")
        assertTrue(abs(snap.weekAgeDaysAfter - state.weekAgeDays) <= 1e-9,
                   "$ctx (window age): expected ${snap.weekAgeDaysAfter}, got ${state.weekAgeDays}")
        assertJournal(state, snap.shownAfter, ctx)
    }

    /** The journal — doubly sparse on both sides, so an entry the port
     *  invented fails as loudly as one it lost. */
    private fun assertJournal(state: EngineState, expected: Map<String, Map<String, Int>>, ctx: String) {
        val actual = state.shown.filterValues { it.isNotEmpty() }
            .map { (p, row) -> p.rawValue to row.mapKeys { it.key.toString() } }.toMap()
        assertEquals(expected, actual, "$ctx (journal of what was shown)")
    }

    private fun assertStreaks(state: EngineState, expected: List<Int>, order: List<Pattern>, ctx: String) {
        assertEquals(expected, order.map { state.failStreak[it] ?: -1 }, "$ctx (failStreak)")
    }

    private fun assertGlobals(state: EngineState, step: Golden.Step, ctx: String) {
        assertEquals(step.counterAfter, state.counter, "$ctx (counter)")
        assertEquals(step.failStreakAfter, Pattern.allCases.map { state.failStreak[it] ?: -1 }, "$ctx (failStreak)")
        assertEquals(step.lessRunAfter, state.lessRun, "$ctx (less run)")
        val hist = state.lessHist.filterValues { it > 0 }.mapKeys { it.key.rawValue }
        assertEquals(step.lessHistAfter, hist, "$ctx (appearance window)")
        assertEquals(step.returnRunAfter, state.returnRun, "$ctx (return run)")
        assertEquals(step.creditPausedAfter,
                     listOf(Pattern.pull, Pattern.pullBar).map { if (it in state.creditPaused) 1 else 0 },
                     "$ctx (credit paused)")
    }

    // MARK: - Small conversions

    private fun patternKeyed(src: Map<String, Int>): MutableMap<Pattern, Int> =
        src.mapKeysTo(mutableMapOf()) { assertNotNull(Pattern.fromRaw(it.key)) }

    private fun decodeShown(src: Map<String, Map<String, Int>>): MutableMap<Pattern, MutableMap<Int, Int>> =
        src.entries.associateTo(mutableMapOf()) { (raw, row) ->
            assertNotNull(Pattern.fromRaw(raw)) to row.mapKeysTo(mutableMapOf()) { it.key.toInt() }
        }
}
