//
//  The wire form of golden.json, and nothing else — the port of
//  ios/DredfitCore/Tests/DredfitCoreTests/GoldenFixture.swift.
//
//  Kept apart from the assertions so a change of the fixture's SHAPE is a diff
//  in one place. The fixture is generated by make_golden.js from the pinned
//  reference adaptive_engine.js; it is never edited by hand, and it is read
//  from the Swift package's Fixtures folder — never copied (core/build.gradle.kts).
//
//  Decoding is STRICT where Swift's `Decodable` is: a required field that is
//  missing fails the load rather than reading as a default, so a fixture that
//  changed shape cannot pass by asserting nothing.
//

package com.dredfit.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int

/** A strict reader of one JSON object: `req*` fails on a missing key, `opt*`
 *  answers null for a missing or null one. */
internal class Wire(private val obj: JsonObject, private val ctx: String) {
    private fun at(key: String): JsonElement =
        obj[key]?.takeIf { it !is JsonNull } ?: error("$ctx: missing required \"$key\"")

    private fun optAt(key: String): JsonElement? = obj[key]?.takeIf { it !is JsonNull }

    fun has(key: String): Boolean = optAt(key) != null
    fun reqString(key: String): String = (at(key) as JsonPrimitive).also { check(it.isString) }.content
    fun reqInt(key: String): Int = (at(key) as JsonPrimitive).int
    fun reqDouble(key: String): Double = (at(key) as JsonPrimitive).double
    fun reqBool(key: String): Boolean = (at(key) as JsonPrimitive).boolean
    fun reqInts(key: String): List<Int> = (at(key) as JsonArray).map { (it as JsonPrimitive).int }
    fun reqObj(key: String): Wire = Wire(at(key) as JsonObject, "$ctx.$key")
    fun reqArray(key: String): JsonArray = at(key) as JsonArray
    fun optBool(key: String): Boolean? = optAt(key)?.let { (it as JsonPrimitive).boolean }
    fun optDouble(key: String): Double? = optAt(key)?.let { (it as JsonPrimitive).double }
    fun optInts(key: String): List<Int>? = if (has(key)) reqInts(key) else null
    fun optStrings(key: String): List<String>? =
        optAt(key)?.let { a -> (a as JsonArray).map { (it as JsonPrimitive).content } }
    fun optObj(key: String): Wire? = if (has(key)) reqObj(key) else null
    fun raw(): JsonObject = obj

    /** `[String: Int]` */
    fun reqIntMap(key: String): Map<String, Int> = reqObj(key).intMap()
    fun optIntMap(key: String): Map<String, Int>? = optObj(key)?.intMap()
    fun intMap(): Map<String, Int> = obj.mapValues { (it.value as JsonPrimitive).int }

    /** `[String: Double]` — a fact arrives as a FRACTION: decoding it as Int
     *  would collapse 7.33 and 7.00 into the same seven. */
    fun reqDoubleMap(key: String): Map<String, Double> =
        reqObj(key).obj.mapValues { (it.value as JsonPrimitive).double }

    /** `[String: [String: Int]]` — the journal of what was shown. */
    fun reqJournal(key: String): Map<String, Map<String, Int>> =
        reqObj(key).obj.mapValues { (it.value as JsonObject).mapValues { v -> (v.value as JsonPrimitive).int } }
}

internal class Golden(
    val generator: String,
    val patternOrder: List<String>,
    /** The ladders, straight from the reference. */
    val library: Map<String, List<LibraryRung>>,
    /** The two dose grids. */
    val dose: Map<String, Grid>,
    val scenarios: List<Scenario>,
) {
    class LibraryRung(val name: String, val w: Double, val unit: String, val perSide: Boolean,
                      val kind: String, val prov: String, val probeOnly: Boolean?)

    class Grid(val min: Int, val max: Int, val step: Int)

    /** Everything a state snapshot carries, at whatever point it was taken —
     *  written at the SAME level as the record's own fields. */
    class Snapshot(w: Wire) {
        val varsAfter = w.reqInts("varsAfter")
        val setsAfter = w.reqInts("setsAfter")
        val dosesAfter = w.reqInts("dosesAfter")
        val subAfter = w.reqInts("subAfter")
        val cutAfter = w.reqInts("cutAfter")
        val shownAfter = w.reqJournal("shownAfter")
        val lastHardAfter = w.reqInts("lastHardAfter")
        val setsHoldAfter = w.reqInts("setsHoldAfter")
        val shownWorkAfter = w.reqInts("shownWorkAfter")
        val shownOrdAfter = w.reqInts("shownOrdAfter")
        val shownCapAfter = w.reqInts("shownCapAfter")
        val shownOwnAfter = w.reqInts("shownOwnAfter")
        val shownSkipAfter = w.reqInts("shownSkipAfter")
        val rampWindowAfter = w.reqInt("rampWindowAfter")
        val weekGainAfter = w.reqInts("weekGainAfter")
        val weekAgeDaysAfter = w.reqDouble("weekAgeDaysAfter")
    }

    class Scenario(val name: String, val steps: List<Step>, val seed: Seed?)

    /** A starting state, so a scenario can exercise behaviour that only
     *  appears after a long history. */
    class Seed(w: Wire) {
        val counter = w.reqInt("counter")
        val hasBar = w.reqBool("hasBar")
        val vars = w.reqInts("vars")
        val sets = w.reqInts("sets")
        val doses = w.reqInts("doses")
        val sub = w.reqInts("sub")
        val cut = w.reqInts("cut")
        val shown = w.reqJournal("shown")
        val failStreak = w.reqInts("failStreak")
        val lastHard = w.reqInts("lastHard")
        val shownWork = w.optIntMap("shownWork")
        val shownOrd = w.optIntMap("shownOrd")
    }

    class Ex(w: Wire) {
        val pattern = w.reqString("pattern")
        val variation = w.reqInt("variation")
        val unit = w.reqString("unit")
        val load = w.reqInt("load")
        val perSide = w.reqBool("perSide")
        val sets = w.reqInt("sets")
        val restSetSec = w.reqInt("restSetSec")
        val restExerciseSec = w.reqInt("restExerciseSec")
        /** Present only on an uneven plan — its absence is a claim too. */
        val loads = w.optInts("loads")
        val probe = w.optObj("probe")?.let { Probe(it) }
    }

    class Probe(w: Wire) {
        val variation = w.reqInt("variation")
        val unit = w.reqString("unit")
        val load = w.reqInt("load")
        val perSide = w.reqBool("perSide")
    }

    /** A step's own fields, beside the snapshot it carries at the same level. */
    class Step(w: Wire) {
        val snapshot = Snapshot(w)
        val sessionNumber = w.reqInt("sessionNumber")
        val estimatedTotalMin = w.reqDouble("estimatedTotalMin")
        val warmupMin = w.reqInt("warmupMin")
        val cooldownMin = w.reqInt("cooldownMin")
        val exercises = w.reqArray("exercises").mapIndexed { i, e -> Ex(Wire(e as JsonObject, "exercises[$i]")) }
        val result = w.reqString("result")
        val overrides = w.reqDoubleMap("overrides")
        /** The SEVENTH argument of applyFeedback. Absent means no probe number. */
        val probes = w.optIntMap("probes")
        val skipped = w.optStrings("skipped")
        val hasBar = w.optBool("hasBar")
        /** The gap. Absent means null, which pins the calendar-blind path. */
        val gapDays = w.optDouble("gapDays")
        val handles = w.optObj("handles")?.let { Handles(it) }
        /** Sets skipped DURING this session. Landed AFTER the feedback. */
        val skipSets = w.optIntMap("skipSets")
        /** The cut the feedback left behind, before the skip was added. */
        val cutBeforeSkip = w.optInts("cutBeforeSkip")
        /** Steps added "for next time", landed LAST. */
        val raiseDose = w.optIntMap("raiseDose")
        val beforeRaise = w.optObj("beforeRaise")?.let { BeforeRaise(it) }
        val silentDecay = w.optObj("silentDecay")?.let { BreakStep(it) }
        val comeback = w.optObj("comeback")?.let { ComebackStep(it) }
        val failStreakAfter = w.reqInts("failStreakAfter")
        val counterAfter = w.reqInt("counterAfter")
        val lessRunAfter = w.reqInt("lessRunAfter")
        val lessHistAfter = w.reqIntMap("lessHistAfter")
        val returnRunAfter = w.reqInt("returnRunAfter")
        val creditPausedAfter = w.reqInts("creditPausedAfter")
    }

    class BeforeRaise(w: Wire) {
        val doses = w.reqInts("doses")
        val sub = w.reqInts("sub")
    }

    /** applySilentDecay invoked before this step's session — and before the
     *  step's comeback when both are present. */
    class BreakStep(w: Wire) {
        val gapDays = w.reqInt("gapDays")
        val failStreakAfter = w.reqInts("failStreakAfter")
        val snapshot = Snapshot(w)
    }

    class Comeback(w: Wire) {
        val gapDays = w.reqInt("gapDays")
        val alreadyDecayed = w.optBool("alreadyDecayed")
        val counterAfter = w.reqInt("counterAfter")
        val failStreakAfter = w.reqInts("failStreakAfter")
        val returnRunAfter = w.reqInt("returnRunAfter")
        val snapshot = Snapshot(w)
    }

    /** One step may carry a SERIES of comebacks; the wire form is either a
     *  single snapshot or `{series: [...]}`. */
    class ComebackStep(w: Wire) {
        val snaps: List<Comeback> = if (w.has("series")) {
            w.reqArray("series").mapIndexed { i, e -> Comeback(Wire(e as JsonObject, "series[$i]")) }
        } else {
            listOf(Comeback(w))
        }
    }

    /** A handle pull: what was pressed, and the snapshot right after. */
    class Handles(w: Wire) {
        val easierVariation = w.optStrings("easierVariation")
        val setCut = w.optIntMap("setCut")
        val snapshot = Snapshot(w)
    }

    companion object {
        fun bytes(resource: String): ByteArray {
            val stream = Golden::class.java.classLoader.getResourceAsStream(resource)
                ?: error("$resource not found in test resources")
            return stream.use { it.readBytes() }
        }

        fun load(): Golden {
            val root = Wire(Json.parseToJsonElement(bytes("golden.json").decodeToString()) as JsonObject, "golden")
            return Golden(
                generator = root.reqString("generator"),
                patternOrder = root.reqArray("patternOrder").map { (it as JsonPrimitive).content },
                library = root.reqObj("library").raw().mapValues { (name, rungs) ->
                    (rungs as JsonArray).mapIndexed { i, r ->
                        val w = Wire(r as JsonObject, "library.$name[$i]")
                        LibraryRung(name = w.reqString("name"), w = w.reqDouble("w"),
                                    unit = w.reqString("unit"), perSide = w.reqBool("perSide"),
                                    kind = w.reqString("kind"), prov = w.reqString("prov"),
                                    probeOnly = w.optBool("probeOnly"))
                    }
                },
                dose = root.reqObj("dose").raw().mapValues { (name, g) ->
                    val w = Wire(g as JsonObject, "dose.$name")
                    Grid(min = w.reqInt("min"), max = w.reqInt("max"), step = w.reqInt("step"))
                },
                scenarios = root.reqArray("scenarios").mapIndexed { i, s ->
                    val w = Wire(s as JsonObject, "scenarios[$i]")
                    Scenario(
                        name = w.reqString("name"),
                        steps = w.reqArray("steps").mapIndexed { j, st ->
                            Step(Wire(st as JsonObject, "${w.reqString("name")}/step ${j + 1}"))
                        },
                        seed = w.optObj("seed")?.let { Seed(it) })
                })
        }
    }
}
