// generated by scripts/export_android_strings.py from android/app/Localizable.xcstrings — do not edit
package com.dredfit.l10n

import com.dredfit.R

/** Resource ids by the English key, as `String(localized:)` looks them up on iOS. */
internal object AndroidStrings {
    fun string(key: String): Int? = strings[key]

    fun plural(key: String): Int? = plurals[key]

    private val strings: Map<String, Int> by lazy { index(stringKeys(), stringIds()) }
    private val plurals: Map<String, Int> by lazy { index(pluralKeys(), pluralIds()) }

    private fun index(keys: Array<String>, ids: IntArray): Map<String, Int> {
        val map = HashMap<String, Int>(keys.size * 2)
        for (i in keys.indices) map[keys[i]] = ids[i]
        return map
    }

    private fun stringKeys(): Array<String> = arrayOf(
        "Open notification settings",
        "Rate on Google Play",
        "The tones play even when the phone is set to silent or vibrate.",
        "When the phone is set to silent or vibrate, the tones go quiet — the vibration keeps going.",
        "Workout in progress",
    )

    private fun stringIds(): IntArray = intArrayOf(
        R.string.android_open_notification_settings_9e8653ce,
        R.string.android_rate_on_google_play_1b86d374,
        R.string.android_the_tones_play_even_when_the_phone_is_se_2f936e1b,
        R.string.android_when_the_phone_is_set_to_silent_or_vibra_a20ca2f7,
        R.string.android_workout_in_progress_90335fa4,
    )

    private fun pluralKeys(): Array<String> = arrayOf<String>()

    private fun pluralIds(): IntArray = intArrayOf()
}
