// generated by scripts/export_android_strings.py from ios/DredfitWidgets/Localizable.xcstrings — do not edit
package com.dredfit.l10n

import com.dredfit.R

/** Resource ids by the English key, as `String(localized:)` looks them up on iOS. */
internal object WidgetStrings {
    fun string(key: String): Int? = strings[key]

    fun plural(key: String): Int? = plurals[key]

    private val strings: Map<String, Int> by lazy { index(stringKeys(), stringIds()) }
    private val plurals: Map<String, Int> by lazy { index(pluralKeys(), pluralIds()) }

    private fun index(keys: Array<String>, ids: IntArray): Map<String, Int> {
        val map = HashMap<String, Int>(keys.size * 2)
        for (i in keys.indices) map[keys[i]] = ids[i]
        return map
    }

    private fun stringKeys(): Array<String> = arrayOf(
        "about %lld to %lld minutes · %lld exercises",
        "Done ✓",
        "Dredfit",
        "%lld",
        "≈ %lld–%lld min",
        "≈ %lld–%lld min · %lld exercises",
        "≈ %lld min",
        "Next workout %@",
        "Next: Workout %lld · %@",
        "Rest day",
        "steps",
        "This week",
        "Today",
        "Today's status",
        "Workout day",
        "Workout, done, or rest day — at a glance.",
        "Workout %lld",
        " · %@",
    )

    private fun stringIds(): IntArray = intArrayOf(
        R.string.widgets_about_lld_to_lld_minutes_lld_exercises_eadff614,
        R.string.widgets_done_a821d153,
        R.string.widgets_dredfit_3e1467ea,
        R.string.widgets_lld_16070acf,
        R.string.widgets_lld_lld_min_b8e827c9,
        R.string.widgets_lld_lld_min_lld_exercises_1deb1360,
        R.string.widgets_lld_min_7c31f2a4,
        R.string.widgets_next_workout_98adf22c,
        R.string.widgets_next_workout_lld_46bb52bc,
        R.string.widgets_rest_day_e3a72d7a,
        R.string.widgets_steps_6578912e,
        R.string.widgets_this_week_7b72883e,
        R.string.widgets_today_24345a14,
        R.string.widgets_today_s_status_3f920d82,
        R.string.widgets_workout_day_6012da42,
        R.string.widgets_workout_done_or_rest_day_at_a_glance_0213893e,
        R.string.widgets_workout_lld_a3eb3f0d,
        R.string.widgets_x_f8e17780,
    )

    private fun pluralKeys(): Array<String> = arrayOf(
        "≈ %lld min · %lld exercises",
        "%lld steps",
        "%lld workouts",
    )

    private fun pluralIds(): IntArray = intArrayOf(
        R.plurals.widgets_lld_min_lld_exercises_f97df2de,
        R.plurals.widgets_lld_steps_bc79b11d,
        R.plurals.widgets_lld_workouts_9c2a68a2,
    )
}
